// Test deserialization with randomly generated bytecode.

#[cfg(feature = "fuzzing")]
mod deserialization {
    use rand::RngCore;
    use watchmaker_vm::*;

    #[test]
    fn fuzz_deserialize_opcodes() {
        for _ in 0..(1 << 10) {
            let raw = rand::thread_rng().next_u64();
            let _: Instruction = deserialize(raw);
        }
    }
}
